emptytime/notice/urls.py
from django.urls import path
from . import views
app_name='notice'
urlpatterns = [
    path('', views.home , name='home'),
    path('email/', views.email, name='email'),
    path('email_control/', views.email_control, name='control'),
    path('agree/', views.agree, name='agree'),
    path('join/', views.signup, name= 'join'),
    path('login/', views.signin, name='login'),
    path('logout/', views.logout, name='logout'),
    path('addTag/', views.addTag, name='addTag'),
    path('delTag/<int:tag_id>',views.delTag, name = 'delTag'),
]

emptytime/notice/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class TitleData(models.Model):
    title = models.CharField(max_length=500)
    link = models.IntegerField()
    def __str__(self):
        return self.title

class KmTitle(models.Model):
    km_title = models.CharField(max_length=500)
    km_link = models.IntegerField()
    def __str__(self):
        return self.km_title

class Mytag(models.Model):
    myTag = models.CharField(max_length=20)
    account = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    def __str__(self):
        return self.myTag

class RecentTagLink(models.Model):
    sw_link = models.IntegerField()
    km_link = models.IntegerField()

emptytime/notice/forms.py
from django.forms import ModelForm
from django import forms
from .models import Mytag
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'input100', 'name': 'id'}
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={'class': 'input100', 'name': 'pass'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'input100', 'name': 'pass'}
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class LoginForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'input100', 'name': 'id'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'input100', 'name': 'pass'}
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password',)

# class EmailForm(ModelForm):
#     class Meta:
#         model = EmailAccount
#         fields = ['myEmail']
#         labels = {
#             'myEmail': _('이메일 입력'),
#         }
#         help_texts = {
#             'myEmail': _('이메일을 입력해주세요.'),
#         }
#
#         error_messages = {
#             'name': {
#                 'max_length': _("이메일이 너무 깁니다. 30자 이하로 해주세요."),
#             },
#         }

class TagForm(ModelForm):
    myTag = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'input100', 'name': 'tag'}
        )
    )

    class Meta:
        model = User
        fields = ('myTag',)

emptytime/notice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TitleData, Mytag, KmTitle
from django.http import HttpResponse
from .forms import UserForm, LoginForm, TagForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as django_logout


def home(request):
    return render(request, 'notice/home.html')


def email(request):
    context = {
        'notice_list': TitleData.objects.all(),
        'km_notice_list': KmTitle.objects.all(),
    }
    return render(request, 'notice/email.html', context)


def email_control(request):
    try:
        user = request.user
        tag_list = Mytag.objects.filter(account=user).all()
        return render(request, 'notice/email_service_control.html', {'tag_list': tag_list})
    except TypeError:
        return render(request, 'notice/userNotFound.html')


def agree(request):
    return render(request, 'notice/agreement.html')


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():

            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('notice:email')
        else:
            return render(request, 'notice/emailError.html')
    else:
        form = UserForm()
        return render(request, 'notice/adduser.html', {'form': form})


def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('notice:email')
        else:
            return render(request, 'notice/error.html')
    else:
        form = LoginForm()
        return render(request, 'notice/login.html', {'form': form})
def logout(request):
    django_logout(request)
    return redirect('notice:email')

def addTag(request):
    if request.method == "POST":
        account = request.user
        form = TagForm(request.POST)
        if form.is_valid():
            post = Mytag(account=account, myTag=form.data['myTag'])
            post.save()
            return redirect('notice:control')
    else:
        form = TagForm()
    return render(request, 'notice/addTag.html', {'form': form})


def delTag(request, tag_id):
    item = get_object_or_404(Mytag, pk=tag_id)
    item.delete()

    return redirect('notice:control')

emptytime/notice/templates/notice/addTag.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>키워드추가</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/fontawesome-free/css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/iconic/css/material-design-iconic-font.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/animate/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css-hamburgers/hamburgers.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/animsition/css/animsition.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/select2/select2.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/daterangepicker/daterangepicker.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/main.css'%}">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-30 p-b-20">
			<span class="login100-form-title p-b-50">
				Add Keyword
			</span>
            <span class="login100-form-avatar">
				<img src="{% static 'timetable/adduser/images/timepushlogo.jpg'%}" alt="AVATAR">
			</span>

            <form method="POST" class="post-form">
                {%csrf_token%}

                <div class="wrap-input100 validate-input m-t-50 m-b-35" data-validate="Enter tag">
                    {{ form.myTag }}
                    <span class="focus-input100" data-placeholder="Keyword"></span>
                </div>

                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn">
                        Save
                    </button>
                </div>

            </form>

            <ul class="login-more p-t-50">
                <li>
					<span class="txt1">
						입력하신 키워드를 모니터링하여 해당 키워드가 제목에 포함된 공지사항이 올라오면 이메일로 알려드립니다.
					</span>
                </li>
                <li>
					<span class="txt1">
						소프트웨어융합대학과 국민대학교 공지사항을 실시간으로 모니터링합니다.
					</span>
                </li>
            </ul>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'lib/animsition/js/animsition.min.js'%}"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'lib/select2/select2.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/moment.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/daterangepicker.js'%}"></script>
<script src="{% static 'lib/countdowntime/countdowntime.js'%}"></script>
<script src="{% static 'timetable/adduser/js/main.js'%}"></script>

</body>
</html>

emptytime/notice/templates/notice/adduser.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>TimePush 회원가입</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/fontawesome-free/css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/iconic/css/material-design-iconic-font.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/animate/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css-hamburgers/hamburgers.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/animsition/css/animsition.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/select2/select2.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/daterangepicker/daterangepicker.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/main.css'%}">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-30 p-b-20">
			<span class="login100-form-title p-b-50">
				TimePush SIGN UP
			</span>
            <span class="login100-form-avatar">
				<img src="{% static 'timetable/adduser/images/timepushlogo.jpg'%}" alt="AVATAR">
			</span>

            <form method="POST" class="post-form">
                {%csrf_token%}

                <div class="wrap-input100 validate-input m-t-50 m-b-35" data-validate="Enter username">
                    {{ form.username }}
                    <span class="focus-input100" data-placeholder="ID"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-35" data-validate="Enter email">
                    {{ form.email }}
                    <span class="focus-input100" data-placeholder="E-Mail"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-50" data-validate="Enter password">
                    {{ form.password }}
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>

                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn">
                        Submit
                    </button>
                </div>

            </form>

            <ul class="login-more p-t-50">
                <li>
					<span class="txt1">
						입력한 이메일 주소로 공지사항 알림을 발송합니다.
					</span>
                </li>
            </ul>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'lib/animsition/js/animsition.min.js'%}"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'lib/select2/select2.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/moment.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/daterangepicker.js'%}"></script>
<script src="{% static 'lib/countdowntime/countdowntime.js'%}"></script>
<script src="{% static 'timetable/adduser/js/main.js'%}"></script>

</body>
</html>

emptytime/notice/templates/notice/email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>공지사항알림</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>
</head>

<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">학교의 최신 공지사항을 확인하고 키워드 알림까지 받아보세요! 시간표합치기 서비스를 이용하시려면 <a class="redirectHome" href="{% url 'notice:home' %}">홈으로</a></div>
        </div>
    </div>
</div>

<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">E-Mail Notice</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">회원가입하고 공지사항 키워드 알림 서비스를 이용해보세요.</h4>
                <div>
                    <p>
                        {% if user.is_active %}
                        <a class="btn btn-lg btn-gradient" href="{% url 'notice:logout' %}">Logout</a><br>
                        {% else %}
                        <a class="btn btn-lg btn-gradient" href="{% url 'notice:agree' %}">Sign Up</a>
                        <a class="btn btn-lg btn-gradient" href="{% url 'notice:login' %}">Sign In</a><br>
                        {% endif %}
                        <a class="btn btn-lg btn-gradient" href="{% url 'notice:control' %}">Manage Keyword</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="space-md w-90 noPadding">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center text-center">
            <div class="col-md-10 mb-md-5 mb-sm-3">
                <h2><strong>공지사항 목록</strong></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div style="overflow: auto"; class="card pricing-v3 p-md-5 p-sm-3 text-center paddingOver">
                    <div class="list-group">
                        <p class="titleNotice">국민대학교</p>
                        {% for km_notice in km_notice_list%}
                        <a href="https://www.kookmin.ac.kr/site/ecampus/notice/all/{{km_notice.km_link}}" class="list-group-item list-group-item-action flex-column align-items-start">
                            <p class="mb-1">{{km_notice.km_title}}</p>
                        </a>
                        {% endfor%}
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card pricing-v3 p-md-5 p-sm-3 text-center paddingOver">
                    <div class="list-group">
                        <p class="titleNotice">소프트웨어융합대학</p>
                        {% for notice in notice_list%}
                        <a href="https://cs.kookmin.ac.kr/news/notice/{{notice.link}}" class="list-group-item list-group-item-action flex-column align-items-start">
                            <p class="mb-1">{{notice.title}}</p>
                        </a>
                        {% endfor%}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
</body>

</html>

emptytime/notice/templates/notice/emailError.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>오류발생</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">에러가 발생했습니다.</a>
            </div>
        </div>
    </div>
</div>
<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">ERROR</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">이미 사용중인 아이디 이거나, 잘못된 이메일 형식입니다. 다시 확인해주세요.</h4>
                <p>
                    <a class="btn btn-lg btn-gradient" href="{% url 'notice:join' %}">Return</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>

emptytime/notice/templates/notice/email_service_control.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>키워드관리</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">원하는 키워드를 자유롭게 입력해보세요! 시간표합치기 서비스를 이용하시려면 <a class="redirectHome" href="{% url 'notice:home' %}">홈으로</a>
            </div>
        </div>
    </div>
</div>

<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">Notice Keyword</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">입력하신 키워드를 모니터링 중입니다. 원하는 공지사항이 올라오면 알려드리겠습니다.</h4>
                {% if tag_list %}
                        <div class="row">
                        {% for tag in tag_list %}
                            <div class="card cardBorder col-md-4 col-sm-6 col-12 text-left">
                              <div class="card-body">
                                <h4 class="card-title resizeCardText">{{ tag.myTag }}</h4>
                                <a href="{% url 'notice:delTag' tag_id=tag.id %}" class="btn btn-primary">Delete</a>
                              </div>
                            </div>
                        {% endfor %}
                        </div>
                {% else %}
                    <p>&nbsp;</p>
                    <p><strong>모니터링 중인 키워드가 없습니다.</strong></p>
                {% endif %}
                <p>
                    <a class="btn btn-lg btn-gradient" href="{% url 'notice:addTag' %}">Add Keyword</a>
                    <a class="btn btn-lg btn-gradient" href="{% url 'notice:email' %}">Notice List</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>

emptytime/notice/templates/notice/error.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>오류발생</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">비밀번호 혹은 아이디의 오탈자를 점검해주세요.</a>
            </div>
        </div>
    </div>
</div>
<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">ERROR</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">로그인에 실패하였습니다. 계정정보를 다시 확인하세요!</h4>
                <p>
                    <a class="btn btn-lg btn-gradient" href="{% url 'notice:login' %}">Return</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>

emptytime/notice/templates/notice/home.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>TimePush</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	<link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

		<link rel="stylesheet" href="{% static 'notice/home/assets/css/main.css'%}" />
		<noscript><link rel="stylesheet" href="{% static 'notice/home/assets/css/noscript.css'%}" /></noscript>

		<link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header" class="homeBack">
				<div class="content">
					<h1>TimePush</h1>
					<p class="homeTitleText">친구들과 겹치는 공강시간을 찾고<br/>
					원하는 학교 공지사항만 이메일로 받아보세요</p>
					<ul class="actions">
						<li><a href="#one" class="button icon solid fa-chevron-down fa-1x scrolly">서비스 소개</a></li>
					</ul>
					<ul class="actions">
						<li><a href="{% url 'timetable:index' %}" class="button primary">시간표합치기</a></li>
						<li><a href="{% url 'notice:email' %}" class="button primary">공지사항알림</a></li>
					</ul>
				</div>
				<div class="image phone"><div class="inner"><img src="{% static 'notice/home/images/screen.jpg'%}" alt="" /></div></div>
			</header>

		<!-- One -->
			<section id="one" class="wrapper style2 special">
					<div class="content">
						<h1 class="homeDiscText">서비스 소개</h1>
					</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper">
				<div class="inner alt">
					<section class="spotlight">
						<div class="image"><img src="{% static 'notice/home/images/pic01.jpg'%}" alt="" /></div>
						<div class="content">
							<h3 class="homeServiceText">시간표합치기</h3>
							<p>국민대학교 종합정보시스템 계정을 입력하고, 입력한 계정들의 시간표 병합결과를 확인하세요. 친구들과 겹치는 공강시간을 확인할 수 있어, 조별과제 미팅시간 정하기나 식사시간 정하기에 효율적으로 사용할 수 있습니다!</p>
						</div>
					</section>
					<section class="spotlight">
						<div class="image"><img src="{% static 'notice/home/images/pic02.jpg'%}" alt="" /></div>
						<div class="content">
							<h3 class="homeServiceText">공지사항알림</h3>
							<p>국민대학교와 소프트웨어융합대학 공지사항을 한눈에 확인하세요. 본인이 원하는 키워드를 미리 등록하여 해당 키워드가 포함된 공지사항이 올라왔을때 회원가입 시 입력하신 이메일로 알림 메일을 발송해드립니다!</p>
						</div>
					</section>
				</div>
			</section>

		<!-- Scripts -->
			<script src="{% static 'lib/jquery.js'%}"></script>
			<script src="{% static 'lib/jquery.scrolly.min.js'%}"></script>
			<script src="{% static 'lib/browser.min.js'%}"></script>
			<script src="{% static 'lib/breakpoints.min.js'%}"></script>
			<script src="{% static 'notice/home/assets/js/util.js'%}"></script>
			<script src="{% static 'notice/home/assets/js/main.js'%}"></script>

	</body>
</html>

emptytime/notice/templates/notice/userNotFound.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Not Found</title>
</head>
<body>
    <h2>로그인 해주세요!</h2>
    <a href="{% url 'notice:email' %}">돌아가기</a>

</body>
</html>