emptytime/timetable/urls.py
from django.urls import path

from . import views

app_name='timetable'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('clearUser/', views.branchHome, name='branch'),
    path('agree/', views.agree, name='agree'),
    path('account/', views.account, name='account'),
    path('account/add/', views.post, name='adduser'),
    path('account/result/', views.result, name='result'),
    path('account/error/', views.error, name='error'),
    path('account/delete/<str:username_text>/', views.delete, name='delete'),
]

emptytime/timetable/models.py
from django.db import models


class User(models.Model):
    token_text = models.CharField(max_length=100, null=True)
    username_text = models.CharField(max_length=8)
    pw_text = models.CharField(max_length=30)


    def __str__(self):
        return self.username_text

emptytime/timetable/forms.py
from django import forms
from .models import User

class PostForm(forms.ModelForm):
    username_text = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'input100', 'name': 'studentid'}
        )
    )
    pw_text = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'input100', 'name': 'pass'}
        )
    )
    class Meta:
        model = User
        fields = ('username_text', 'pw_text',)

emptytime/timetable/views.py
from django.shortcuts import get_object_or_404, render, redirect
from selenium.common.exceptions import UnexpectedAlertPresentException
from .models import User
from .forms import PostForm
import re
import time
import os
from selenium import webdriver
from bs4 import BeautifulSoup


def index(request):
    token = str(time.time())
    request.session['token'] = token
    return redirect('timetable:agree')


def branchHome(request):
    token = request.session.get('token')
    user_list = User.objects.filter(token_text=token)
    user_list.delete()
    return redirect('notice:home')


def agree(request):
    return render(request, 'timetable/agreement.html')


def account(request):
    token = request.session.get('token')
    user_list = User.objects.filter(token_text=token)
    return render(request, 'timetable/index.html', {'user_list': user_list})


def post(request):
    token = request.session.get('token')
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = User(token_text=token, username_text=form.data['username_text'], pw_text=form.data['pw_text'])
            post.save()
            return redirect('timetable:account')
    else:
        form = PostForm()
    return render(request, 'timetable/forms.html', {'form': form})


def delete(request, username_text):
    token = request.session.get('token')
    user = get_object_or_404(User, token_text=token, username_text=username_text)
    user.delete()
    return redirect('timetable:account')


def error(request):
    return render(request, 'timetable/error.html')


def result(request):
    token = request.session.get('token')
    driver_path = os.path.join(os.path.dirname(__file__), 'chromedriver')
    options = webdriver.ChromeOptions()
    options.add_argument('headless')
    options.add_argument('window-size=1920x1080')
    options.add_argument("disable-gpu")
    options.add_argument('no-sandbox')
    options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36")
    driver = webdriver.Chrome(driver_path, chrome_options=options)
    def parse_table(username, pw):
        driver.get('https://ktis.kookmin.ac.kr')

        input_element = driver.find_element_by_name("txt_user_id")
        input_element.send_keys(username)
        input_element = driver.find_element_by_name("txt_passwd")
        input_element.send_keys(pw)
        try:
            input_element.submit()
            driver.get('https://ktis.kookmin.ac.kr/kmu/usb.Usb0102rAGet01.do')
        except UnexpectedAlertPresentException:
            return ['error']

        driver.get('https://ktis.kookmin.ac.kr/kmu/usb.Usb0102rAGet01.do')

        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')

        tables = soup.findAll("table")[1]

        tr_list = tables.select("tr")[8:]
        tr_list = tr_list[:-1]

        temp_list = list()

        for tr in tr_list:
            td = tr.select("td")[6]
            string = td.text.replace(", ", ",").replace("7호관", "칠호관")
            temp_list += string.split()

        final_list = list()

        eng_pattern = re.compile(r"[월,화,수,목,금,토][A-Z]")
        num_pattern = re.compile(r"[월,화,수,목,금,토]\d{1,2}")

        for i in temp_list:
            i = re.sub(",", i[0], i)
            match = eng_pattern.findall(i)
            final_list.extend(match)
            match = num_pattern.findall(i)
            final_list.extend(match)

        return final_list

    def processed_table(table_list):
        table_dic = {"0": ["08:00", "09:00"], "1": ["09:00", "10:00"], "2": ["10:00", "11:00"], "3": ["11:00", "12:00"],
                     "4": ["12:00", "13:00"], "5": ["13:00", "14:00"], "6": ["14:00", "15:00"], "7": ["15:00", "16:00"],
                     "8": ["16:00", "17:00"], "9": ["17:00", "18:00"], "10": ["18:00", "18:55"],
                     "11": ["18:55", "19:50"],
                     "12": ["19:50", "20:45"], "13": ["20:45", "21:40"], "14": ["21:40", "22:30"],
                     "A": ["09:00", "10:30"],
                     "B": ["10:30", "12:00"], "C": ["12:00", "13:30"], "D": ["13:30", "15:00"], "E": ["15:00", "16:30"],
                     "F": ["16:30", "18:00"], "G": ["18:00", "19:25"], "H": ["19:25", "20:50"], "I": ["20:50", "22:05"]}
        table_list = sorted(list(set(table_list)))
        mon = list()
        tue = list()
        wed = list()
        thu = list()
        fri = list()
        sat = list()
        for i in table_list:
            if i[0] == "월":
                mon.append(table_dic[i[1:]])
            elif i[0] == "화":
                tue.append(table_dic[i[1:]])
            elif i[0] == "수":
                wed.append(table_dic[i[1:]])
            elif i[0] == "목":
                thu.append(table_dic[i[1:]])
            elif i[0] == "금":
                fri.append(table_dic[i[1:]])
            elif i[0] == "토":
                sat.append(table_dic[i[1:]])

        return mon, tue, wed, thu, fri, sat

    def convert_json(mon, tue, wed, thu, fri, sat):
        def list_to_json(lists, date):
            out_list = str()
            for val in lists:
                out_list += time_to_json(val, date)
            return out_list


        def time_to_json(val, date):
            out_str = str()
            out_str += date
            out_str += "T"
            out_str += val[0]
            out_str += ":00"
            out_str += date
            out_str += "T"
            out_str += val[1]
            out_str += ":00"
            return out_str


        out_list = str()
        out_list += list_to_json(mon, '1970-01-05')
        out_list += list_to_json(tue, '1970-01-06')
        out_list += list_to_json(wed, '1970-01-07')
        out_list += list_to_json(thu, '1970-01-08')
        out_list += list_to_json(fri, '1970-01-09')
        out_list += list_to_json(sat, '1970-01-10')
        return out_list

    timetables = list()
    users = User.objects.filter(token_text=token)
    for i in users:
        timetables.extend(parse_table(i.username_text, i.pw_text))
    driver.quit()

    if 'error' in timetables:
        return redirect('timetable:error')

    users.delete()

    mon, tue, wed, thu, fri, sat = processed_table(timetables)
    del timetables
    return render(request, 'timetable/result.html', {'result_json': convert_json(mon, tue, wed, thu, fri, sat)})

emptytime/timetable/templates/timetable/error.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>오류발생</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">비밀번호 혹은 학번의 오탈자를 점검해주세요.</a>
            </div>
        </div>
    </div>
</div>
<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">ERROR</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">잘못된 계정이 포함되어 있습니다. 계정정보를 다시 확인하세요!</h4>
                <p>
                    <a class="btn btn-lg btn-gradient" href="{% url 'timetable:account' %}">Return</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>

emptytime/timetable/templates/timetable/forms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>종합정보시스템 계정추가</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/fontawesome-free/css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/iconic/css/material-design-iconic-font.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'lib/animate/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css-hamburgers/hamburgers.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/animsition/css/animsition.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/select2/select2.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/daterangepicker/daterangepicker.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'timetable/adduser/css/main.css'%}">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-30 p-b-20">
			<span class="login100-form-title p-b-50">
				KTIS Account
			</span>
            <span class="login100-form-avatar">
				<img src="{% static 'timetable/adduser/images/kmulogo.jpg'%}" alt="AVATAR">
			</span>

            <form method="POST" class="post-form">
                {%csrf_token%}

                <div class="wrap-input100 validate-input m-t-50 m-b-35" data-validate="Enter username">
                    {{ form.username_text }}
                    <span class="focus-input100" data-placeholder="Student ID"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-50" data-validate="Enter password">
                    {{ form.pw_text }}
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>

                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn">
                        Login
                    </button>
                </div>

            </form>

            <ul class="login-more p-t-50">
                <li>
					<span class="txt1">
						계정을 잘못 입력할 경우 시간표 계산이 진행되지 않습니다.
					</span>
                </li>

                <li>
					<span class="txt1">
						입력하신 계정은 시간표 계산 이후 서버에서 완전히 삭제됩니다.
					</span>
                </li>
            </ul>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'lib/animsition/js/animsition.min.js'%}"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'lib/select2/select2.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/moment.min.js'%}"></script>
<script src="{% static 'lib/daterangepicker/daterangepicker.js'%}"></script>
<script src="{% static 'lib/countdowntime/countdowntime.js'%}"></script>
<script src="{% static 'timetable/adduser/js/main.js'%}"></script>

</body>
</html>

emptytime/timetable/templates/timetable/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>시간표합치기</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">합칠 계정들을 추가하고 'Merge Table' 버튼을 눌러보세요! 공지사항알림 서비스를 이용하시려면 <a class="redirectHome" href="{% url 'timetable:branch' %}">홈으로</a>
            </div>
        </div>
    </div>
</div>

<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">Merge Table</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">
                    친구들과 시간표를 합쳐줍니다. 겹치는 공강시간을 찾아보세요!<br>
                    최초 접속 후 15분 안에 병합을 수행하지 않으면 입력하신 계정은 자동 삭제 됩니다.
                </h4>
                {% if user_list %}
                        <div class="row">
                        {% for username in user_list %}
                            <div class="card cardBorder col-md-4 col-sm-6 col-12 text-left">
                              <div class="card-body">
                                <h4 class="card-title resizeCardText">{{ username.username_text }}</h4>
                                <a href="{% url 'timetable:delete' username_text=username.username_text %}" class="btn btn-primary">Delete</a>
                              </div>
                            </div>
                        {% endfor %}
                        </div>
                {% else %}
                    <p>&nbsp;</p>
                    <p><strong>추가한 학생이 없습니다.</strong></p>
                {% endif %}
                <p>
                    <a class="btn btn-lg btn-gradient" href="{% url 'timetable:adduser' %}">Add Student</a>
                    <a class="btn btn-lg btn-gradient" href="{% url 'timetable:result' %}">Merge Table</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>

emptytime/timetable/templates/timetable/result.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <title>시간표 병합결과</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{% static 'lib/favicon.ico'%}"/>

    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <link href="{% static 'lib/fontawesome-free/css/all.min.css'%}" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic"
          rel="stylesheet" type="text/css">
    <link href="{% static 'lib/simple-line-icons/css/simple-line-icons.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/css/style.min.css'%}" rel="stylesheet">

    <link href="{% static 'timetable/result/packages/core/main.css'%}" rel='stylesheet'/>
    <link href="{% static 'timetable/result/packages/daygrid/main.css'%}" rel='stylesheet'/>
    <link href="{% static 'timetable/result/packages/timegrid/main.css'%}" rel='stylesheet'/>
    <link href="{% static 'timetable/result/packages/list/main.css'%}" rel='stylesheet'/>

    <link href="{% static 'timetable/overlap_full.css'%}" rel='stylesheet'/>

    <script>
        function calendarShot() {
            window.scrollTo(0, 0);
            html2canvas(document.getElementById("calendar"))
                .then(function (canvas) {
                    drawImg(canvas.toDataURL('image/jpeg'));
                    saveAs(canvas.toDataURL(), 'emptytime.jpg');
                }).catch(function (err) {
                console.log(err);
            });
        }

        function drawImg(imgData) {
            console.log(imgData);
            return new Promise(function reslove() {
                var canvas = document.getElementById('canvas');
                var ctx = canvas.getContext('2d');
                ctx.clearRect(0, 0, canvas.width, canvas.height);

                var imageObj = new Image();
                imageObj.onload = function () {
                    ctx.drawImage(imageObj, 10, 10);
                };
                imageObj.src = imgData;

            }, function reject() {
            });

        }

        function saveAs(uri, filename) {
            var link = document.createElement('a');
            if (typeof link.download === 'string') {
                link.href = uri;
                link.download = filename;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            } else {
                window.open(uri);
            }
        }

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');

            var list = "{{result_json}}";
            var eventList = [];
            console.log(list);
            for (var i = 0; i < list.length; i += 38) {
                var event = {
                    "start": list.substring(i, i + 19),
                    "end": list.substring(i + 19, i + 38),
                };
                eventList.push(event);
            }
            console.log(eventList);

            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: ['timeGrid'],
                header: {
                    left: "",
                    center: "",
                    right: "",
                },
                defaultView: "timeGridWeek",
                defaultDate: '1970-01-05',
                navLinks: true,
                columnHeaderFormat: {
                    weekday: 'short',
                },
                height: "auto",
                hiddenDays: [0],
                weekNumbers: false,
                weekNumbersWithinDays: false,
                weekNumberCalculation: 'ISO',
                allDaySlot: false,
                slotDuration: '00:30:00',
                minTime: '08:00:00',
                maxTime: '23:00:00',
                editable: true,
                eventLimit: true,
                events: eventList
            });

            calendar.render();
        });

    </script>
    <style>

        #calendar {
            max-width: 900px;
            margin: 0 auto;
        }

    </style>

</head>
<body>

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-9">생성된 시간표를 저장하고 싶으신가요? 하단의 'Save as JPEG' 버튼을 이용해보세요!
            </div>
        </div>
    </div>
</div>

<section class="hero space-md">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <div class="title-content-warpper">
                    <h1 class="resizeMainText">Merged Timetable</h1>
                </div>
                <h4 class="mt-3 mb-3 fixText">색칠된 시간을 피해 약속을 잡아보세요!</h4>
                <div id="calendar"></div>
                <p>
                    <a id="saveImage" class="btn btn-lg btn-gradient" onclick=calendarShot()>Save as JPEG</a>
                    <a class="btn btn-lg btn-gradient" href="{% url 'notice:home' %}">Move to Home</a>
                </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'timetable/result/packages/core/main.js'%}"></script>
<script src="{% static 'timetable/result/packages/interaction/main.js'%}"></script>
<script src="{% static 'timetable/result/packages/daygrid/main.js'%}"></script>
<script src="{% static 'timetable/result/packages/timegrid/main.js'%}"></script>
<script src="{% static 'timetable/result/packages/list/main.js'%}"></script>
<script src="{% static 'lib/jquery.js'%}"></script>
<script src="{% static 'lib/html2canvas.js'%}"></script>
<script src="{% static 'timetable/result/js/style.js'%}"></script>

</body>
</html>